### ISSUE TITLE
How to generate the depth images?

### ISSUE THREAD

**Issue by tpzou** [BoyanJIANG/LoRD#4]
Hi, I find it seems no depth data in the raw CAPE dataset.  Would you mind providing the code for generating the depth images?

**Comment by remmel** [comment]
Which precise file/folder are you talking about?
for example `LoRD/dataset/00134_longlong_twist_trial2_21/depth_pcl/0000.ply` is created by `PYTHONPATH=. python scripts/depth2pcl.py` (and `LoRD/dataset/00134_longlong_twist_trial2_21/body_mesh/*.ply` by `PYTHONPATH=. python scripts/cape_data_process.py`)

**Comment by tpzou** [comment]
I mean how to generate the `depth_image.png`  in `./data/demo/00134_longlong_twist_trial2_21/rendering`?

**Comment by BoyanJIANG** [comment]
Hi @tpzou ,

I just uploaded the codes for rendering the depth images, please check `scripts/render.py` and the related instruction updated in README.

**Comment by tpzou** [comment]
Thanks for your quick reply!

I have two more questions: 
1. It seems only point cloud training is being offered. Can we only train the model with depth images?
2. I find it seems no data processing code of the raw CAPE dataset in the repository, such as `./data/train_800_parts.pt`. Could you provide the train codes of the raw CAPE?

**Comment by tpzou** [comment]
hi, @BoyanJIANG .
When I observed the generated results, I encountered a very confusing problem.  As shown in the figure below, the foot deformation of **blazer** is severe. Is this normal?

![fc6eb253d1adc74d622f6153ed1f0ca](https://user-images.githubusercontent.com/54886980/188535238-b65760de-3925-4518-94b3-8d683b428882.jpg)

**Comment by BoyanJIANG** [comment]
Hi @tpzou,

Thanks a lot for your interest!

1. I haven't tried training with depth data only, but I think it would work, since providing the complete shape at training time is not necessary to learn the deformation within the local parts.
2. I updated the code for sampling part centers in `scripts` folder (the added `smpl_vert_segmentation.json` in `data` folder is needed).
3. Some sequences provided in the CAPE dataset do have this problem, I guess it is because that the captured raw scan data contain noise around hands or feet, resulting in imperfect body fitting.
